# Generated by Django 5.1.4 on 2026-08-15 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0006_alter_membresiaasignada_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_evento', to='gimnasioApp.gimnasio')),
            ],
            options={
                'verbose_name': 'TipoEvento',
                'verbose_name_plural': 'TipoEventos',
                'db_table': 'tipo_evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('relacion_tipo', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('relacion_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='gimnasioApp.gimnasio')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='gimnasioApp.tipoevento')),
            ],
            options={
                'verbose_name': 'EventoCalendario',
                'verbose_name_plural': 'EventoCalendarios',
                'db_table': 'evento_calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
