# Generated by Django 5.2.16 on 2026-08-18 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0007_tipoevento_eventocalendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiaasignada',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECADO: ya no es la fuente de verdad para notificaciones. Usar el modelo Notification.', null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('por_vencer', 'Por vencer'), ('vencida', 'Vencida'), ('evento', 'Evento')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField()),
                ('relacion_tipo', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('relacion_id', models.IntegerField(blank=True, null=True)),
                ('link', models.TextField()),
                ('whatsapp_link', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gimnasioApp.gimnasio')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('gimnasio', 'relacion_tipo', 'relacion_id', 'tipo'), name='uq_notification_idempotency')],
            },
        ),
    ]
