# Generated by Django 5.1.4 on 2026-08-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0009_demorequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.CharField(choices=[('recepcion', 'Recepcionista'), ('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='recepcion', max_length=10),
        ),
    ]
