# Generated by Django 5.1.4 on 2026-08-22 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0010_alter_usuario_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gimnasioApp.gimnasio'),
        ),
    ]
