# Generated by Django 5.1.4 on 2026-08-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0011_alter_usuario_gimnasio'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='gym_creado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_origen', to='gimnasioApp.gimnasio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
