# Generated by Django 5.1.4 on 2026-09-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0012_demorequest_gym_creado_usuario_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresiaasignada',
            name='notified_at',
        ),
    ]
