# Generated by Django 5.1.4 on 2026-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0013_remove_membresiaasignada_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='country_code',
            field=models.CharField(blank=True, default='57', max_length=5),
        ),
    ]
