# Generated by Django 5.1.4 on 2026-10-07 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0014_gimnasio_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('suspender', 'Suspender'), ('cambiar_plan', 'Cambiar Plan'), ('devolucion', 'Devolucion'), ('renovar', 'Renovar')], help_text='Type of operation performed', max_length=20)),
                ('reason', models.TextField(help_text='Verbatim reason provided for the operation')),
                ('details', models.JSONField(default=dict, help_text='Schema per operation_type (REQ-4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gimnasio', models.ForeignKey(help_text='Gym owning this log entry (tenant scope)', on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='gimnasioApp.gimnasio')),
                ('membresia_asignada', models.ForeignKey(help_text='Original assignment (for renovar, this is the original, not the new one)', on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='gimnasioApp.membresiaasignada')),
                ('usuario', models.ForeignKey(blank=True, help_text='User who performed the operation (nullable for system actors)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OperationLog',
                'verbose_name_plural': 'OperationLogs',
                'db_table': 'operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gimnasio', 'created_at'], name='oplog_gym_created_idx'), models.Index(fields=['membresia_asignada', 'created_at'], name='oplog_assignment_created_idx')],
            },
        ),
    ]
