# Generated by Django 5.1.4 on 2026-10-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0015_alter_demorequest_estado_operationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'OperationLog', 'verbose_name_plural': 'OperationLogs'},
        ),
    ]
